Resources:
  generateReportRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ${self:service.name}-${self:provider.stage}-generateReportRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ${self:service.name}-${self:provider.stage}-generateReportPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - 'Fn::Join':
                      - ':'
                      - - 'arn:aws:logs'
                        - Ref: 'AWS::Region'
                        - Ref: 'AWS::AccountId'
                        - 'log-group:/aws/lambda/*:*:*'
              - Effect: Allow
                Action:
                  - s3:getObject
                  - s3:putObject
                  - s3:listBucket
                  - s3:listBucketVersions
                Resource:
                  - arn:aws:s3:::${self:provider.environment.REPORTS_BUCKET_NAME}
                  - arn:aws:s3:::${self:provider.environment.REPORTS_BUCKET_NAME}/*
